# DDNS Clienter config.toml example

[addresses]
[addresses.gateway_ipv4_only]
provider = "ipify"
ipv6 = false

[addresses.self_public_ipv6_only]
provider = "noip"
ipv4 = false
#ipv6_match_rule = "^240e:xxxx"

[addresses.rex_mbp]
provider = "hostname"
parameter = "rex-mbp"
ipv6_match_rule = "^240e:"


[domains]
[domains.update_ipv4_public_address]
provider = "dynv6"
provider_token = "this-is-token-for-this-zone"
domain = "example.com"
host = "@"

address_name = "gateway_ipv4_only"
ipv6 = false

[domains.update_ipv6_public_address]
provider = "dynv6"
provider_token = "this-is-token-for-this-zone"
domain = "example.com"
host = "@"

address_name = "rex_mbp"
ipv4 = false
