# DDNS Clienter config.toml example

[addresses]
[addresses.mibox3]
provider = "hostname"
parameter = "mibox3"

[addresses.gateway_ipv4_only]
provider = "noip"
ipv6 = false

[addresses.rex_mbp]
provider = "hostname"
parameter = "rex-mbp"
ipv4 =false
ipv6_match_rule = "^240e:"


[tasks]
[tasks.update_ipv4_public_address]
dns_provider = "dynv6"
dns_token = "this-is-token-for-this-zone"
domain = "example.com"
host = "@"

address_name = "gateway_ipv4_only"
ipv6 = false

[tasks.update_ipv6_public_address]
dns_provider = "dynv6"
dns_token = "this-is-token-for-this-zone"
domain = "example.com"
host = "@"

address_name = "rex_mbp"
ipv4 = false
