# DDNS Clienter config.toml example

[addresses]

[addresses.from_hostname]
ipv4 = true
ipv6 = true
provider = "hostname"
parameter = "ds216plus"
ipv6_match_rule = "^240e:"

[addresses.from_ipify]
ipv4 = true
ipv6 = true
provider = "ipify"

[addresses.from_noip]
ipv4 = true
provider = "noip"


[domains]

[domains.ipv4_to_dynv6]
ipv4 = true
address_name = "from_ipify"

provider = "dynv6"
provider_token = "this-is-token-for-this-zone"

domain = "example.com"
host = "@"

[domains.ipv6_to_dynv6]
ipv6 = true
address_name = "from_hostname"

provider = "dynv6"
provider_token = "this-is-token-for-this-zone"

domain = "example.com"
host = "@"
