FROM python:3.12-alpine

ARG ENV

RUN if [ "$ENV" = "rex" ]; then echo "Change depends" \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/ \
    && pip config set install.trusted-host pypi.tuna.tsinghua.edu.cn \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    ; fi

#COPY ddns_clienter /app/ddns_clienter
#COPY ddns_clienter_core /app/ddns_clienter_core
COPY requirements /app/requirements
#COPY manage.py /app
#COPY runserver.py /app
#COPY entrypoint.sh /app

# depends
RUN \
    # install depends \
    apk add --no-cache --virtual .build-deps build-base libffi-dev \
    # -- for i18n
    && apk add --no-cache gettext \
    # -- for py
    && pip install --no-cache-dir -r /app/requirements/docker.txt \
    # cleanup --- \
    && apk del .build-deps \
    && rm -rf /root/.cache \
    && find /usr/local/lib/python*/ -type f -name '*.py[cod]' -delete \
    && find /usr/local/lib/python*/ -type d -name "__pycache__" -delete \
    # prepare data path --- \
    && mkdir /data \
    && mkdir /data/lexicon_tld_set \
    && chown nobody:nobody -R /data