FROM ray1ex/ddns-clienter-base

COPY ddns_clienter /app/ddns_clienter
COPY ddns_clienter_core /app/ddns_clienter_core
#COPY requirements /app/requirements
COPY manage.py /app
COPY runserver.py /app
COPY entrypoint.sh /app

WORKDIR /app
EXPOSE 8000

ENV PYTHONPATH=/app
ENV DATA_DIR=/data
ENV DJANGO_SETTINGS_MODULE="ddns_clienter.settings"
ENV SENTRY_DSN=""
ENV WORK_IN_CONTAINER="true"
ENV TLDEXTRACT_CACHE_PATH=/data/lexicon_tld_set

# i18n
RUN ./manage.py compilemessages --ignore venv \
    && ./manage.py collectstatic --no-input

CMD /app/entrypoint.sh

LABEL org.opencontainers.image.title="DDNS Clienter"
LABEL org.opencontainers.image.authors="Rex Zhang"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/ray1ex/ddns-clienter"
LABEL org.opencontainers.image.source="https://github.com/rexzhang/ddns-clienter"
