[common]
sentry_dsn = "https://sentry_dsn@sentry.io/1234567890"

[[address]]
name = "from_openwrt" # task 中识别使用,需要唯一

provider_name = "openwrt-ubus-rpc"                           # openwrt-ubus-rpc 表示通过 OpenWRT ubus RPC 协议获取 IP 地址
provider_parameter = "http://root:password@192.168.1.1/ubus" # ubus RPC 地址格式: http://用户名:密码@IP/ubus, 支持 https, 同时支持自签名的证书

ipv4 = true # 是否获取 IPv4 地址, 默认不获取
ipv6 = true # 是否获取 IPv6 地址, 默认不获取

[[address]]
name = "from_hostname"

provider_name = "hostname" # hostname 表示通过主机名获取 IP 地址
provider_parameter = "localhost" # 设备主机名, 常见的主机名类似: ds216, windows7 ...

ipv4 = true
ipv6 = true
ipv6_match_rule = "^240e:" # 一个主机通常同时会有多个 IPv6 地址, 大概率会包含没有什么用处的私有地址, 可以使用正则表达式进行筛选

[[address]]
name = "from_ipify"

provider_name = "ipify" # 通过 ipify 这个服务商的网络在线服务获取 IP 地址

ipv4 = true
ipv6 = true

[[address]]
name = "from_noip"

provider_name = "noip"

ipv4 = true
ipv6 = true

[[task]]
enable = false
name = "disabled"

address_name = "public_ip"
domain = "disabled.example.com"

provider_name = "dynv6"
provider_auth = "this_is_token_for_this_zone"

ipv4 = true

[[task]]
name = "ipv4_to_dynv6"

domain = "www4.example.com" # 更新 IP 地址到指定的域名
provider_name = "dynv6" # DNS 服务商
provider_auth = "this_is_token_for_this_zone" # DNS 服务商的认证信息

address_name = "from_openwrt" # 使用 from_openwrt 这个地址来源获取的 IP 地址
ipv4 = true # 是否更新 IPv4 地址, 默认不更新

[[task]]
name = "ipv6_to_dynv6"

domain = "www6.example.com"
provider_name = "dynv6"
provider_auth = "this_is_token_for_this_zone"

address_name = "from_hostname"
ipv6 = true # 是否更新 IPv6 地址, 默认不更新

[[task]]
name = "ipv4_to_lexicon_cloudflare"

domain = "www4.example.com"
provider_name = "lexicon.cloudflare"
provider_auth = "auth_token:this_is_token_for_this_zone"

address_name = "from_ipify"
ipv4 = true

[[task]]
name = "ipv6_to_lexicon_cloudflare"

domain = "www6.example.com"
provider_name = "lexicon.cloudflare"
provider_auth = "auth_username:name@example.com,auth_token:this_is_token_for_this_zone"

address_name = "from_hostname"
ipv6 = true
