[common]
sentry_dsn = "https://sentry_dsn@sentry.io/1234567890"

[[address]]
name = "from_openwrt"

provider_name = "openwrt-ubus-rpc"
provider_parameter = "http://root:password@192.168.1.1/ubus"

ipv4 = true
ipv6 = true

[[address]]
name = "from_hostname"

provider_name = "hostname"
provider_parameter = "localhost"

ipv4 = true
ipv6 = true
ipv6_match_rule = "^240e:"

[[address]]
name = "from_ipify"

provider_name = "ipify"

ipv4 = true
ipv6 = true

[[address]]
name = "from_noip"

provider_name = "noip"

ipv4 = true
ipv6 = true

[[task]]
enable = false
name = "disabled"

address_name = "public_ip"
domain = "disabled.example.com"

provider_name = "dynv6"
provider_auth = "this_is_token_for_this_zone"

ipv4 = true

[[task]]
name = "ipv4_to_dynv6"

address_name = "from_ipify"
ipv4 = true
domain = "www4.example.com"

provider_name = "dynv6"
provider_auth = "this_is_token_for_this_zone"

[[task]]
name = "ipv6_to_dynv6"

address_name = "from_hostname"
ipv6 = true
domain = "www6.example.com"

provider_name = "dynv6"
provider_auth = "this_is_token_for_this_zone"

[[task]]
name = "ipv4_to_lexicon_cloudflare"

address_name = "from_ipify"
ipv4 = true
domain = "www4.example.com"

provider_name = "lexicon.cloudflare"
provider_auth = "auth_token:this_is_token_for_this_zone"

[[task]]
name = "ipv6_to_lexicon_cloudflare"

address_name = "from_hostname"
ipv6 = true
domain = "www6.example.com"

provider_name = "lexicon.cloudflare"
provider_auth = "auth_username:name@example.com,auth_token:this_is_token_for_this_zone"
