# Generated by Django 5.2.8 on 2025-11-16 12:34

import uuid_backport._backport
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("enable", models.BooleanField(default=True)),
                ("provider_name", models.CharField(max_length=255)),
                ("provider_parameter", models.TextField()),
                ("ipv4", models.BooleanField()),
                ("ipv4_match_rule", models.TextField()),
                ("ipv6", models.BooleanField()),
                ("ipv6_prefix_length", models.IntegerField(null=True)),
                ("ipv6_match_rule", models.TextField()),
                ("allow_private", models.BooleanField()),
                ("allow_loopback", models.BooleanField()),
                ("ipv4_previous_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_change_time", models.DateTimeField(null=True)),
                ("ipv6_previous_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_change_time", models.DateTimeField(null=True)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid_backport._backport.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ]
                    ),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("key", models.TextField()),
                ("value", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("enable", models.BooleanField(default=True)),
                ("address_name", models.CharField(max_length=255)),
                ("ipv4", models.BooleanField()),
                ("ipv6", models.BooleanField()),
                ("provider_name", models.CharField(max_length=255)),
                ("provider_auth", models.TextField()),
                ("domain", models.CharField(max_length=255)),
                ("previous_ip_addresses", models.TextField(max_length=62, null=True)),
                ("last_ip_addresses", models.CharField(max_length=62)),
                ("last_update_time", models.DateTimeField(null=True)),
                ("last_update_success", models.BooleanField(default=False)),
                ("last_update_success_time", models.DateTimeField(null=True)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
