# Generated by Django 6.0rc1 on 2025-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="time",
            new_name="updated_time",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="time",
            new_name="updated_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
        migrations.RemoveField(
            model_name="status",
            name="id",
        ),
        migrations.AlterField(
            model_name="status",
            name="key",
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
