# DDNS Clienter config.toml example

[addresses]

[addresses.from_hostname]
ipv4 = true
ipv6 = true
ipv6_match_rule = "^240e:"

provider_name = "hostname"
provider_parameter = "localhost"

[addresses.from_ipify]
ipv4 = true
ipv6 = true

provider_name = "ipify"

[addresses.from_noip]
ipv4 = true
ipv6 = true

provider_name = "noip"

[tasks]

[tasks.ipv4_to_dynv6]
ipv4 = true
address_name = "from_ipify"

domain = "example.com"
host = "@"

provider_name = "dynv6"
provider_auth = "this-is-token-for-this-zone"

[tasks.ipv6_to_dynv6]
ipv6 = true
address_name = "from_hostname"

domain = "example.com"
host = "@"

provider_name = "dynv6"
provider_auth = "this-is-token-for-this-zone"

[tasks.ipv4_to_lexicon_cloudflare]
ipv4 = true
address_name = "from_ipify"

domain = "example.com"
host = "host-4"

provider_name = "lexicon.cloudflare"
provider_auth = "auth_token:this-is-token-for-this-zone"

[tasks.ipv6_to_lexicon_cloudflare]
ipv6 = true
address_name = "from_hostname"

domain = "example.com"
host = "host-6"

provider_name = "lexicon.cloudflare"
provider_auth = "auth_username:name@example.com,auth_token:this-is-token-for-this-zone"
