# Generated by Django 3.2.9 on 2021-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("provider", models.CharField(max_length=255)),
                ("parameter", models.TextField()),
                ("ipv4", models.BooleanField()),
                ("ipv6", models.BooleanField()),
                ("ipv4_match_rule", models.TextField()),
                ("ipv6_match_rule", models.TextField()),
                ("ipv4_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_change_time", models.DateTimeField(null=True)),
                ("ipv6_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_change_time", models.DateTimeField(null=True)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("provider", models.CharField(max_length=255)),
                ("provider_token", models.TextField()),
                ("domain", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("address_name", models.CharField(max_length=255)),
                ("ipv4", models.BooleanField()),
                ("ipv6", models.BooleanField()),
                ("last_ip_addresses", models.TextField(max_length=62)),
                ("ip_addresses", models.CharField(max_length=62)),
                ("ip_addresses_is_up_to_date", models.BooleanField()),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
        ),
    ]
