# Generated by Django 3.2.9 on 2021-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=255)),
                ("parameter", models.TextField()),
                ("ipv4", models.BooleanField()),
                ("ipv6", models.BooleanField()),
                ("ipv4_match_rule", models.TextField()),
                ("ipv6_match_rule", models.TextField()),
                ("ipv4_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_address", models.CharField(max_length=15, null=True)),
                ("ipv4_last_change_time", models.DateTimeField(null=True)),
                ("ipv6_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_address", models.CharField(max_length=45, null=True)),
                ("ipv6_last_change_time", models.DateTimeField(null=True)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ]
                    ),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=255)),
                ("provider_token", models.TextField()),
                ("domain", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("address_name", models.CharField(max_length=255)),
                ("ipv4", models.BooleanField()),
                ("ipv6", models.BooleanField()),
                ("ip_addresses", models.CharField(max_length=62)),
                ("last_ip_addresses", models.TextField(max_length=62, null=True)),
                ("last_update_is_success", models.BooleanField()),
                ("last_update_time", models.DateTimeField()),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
