# Generated by Django 4.0 on 2021-12-14 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0002_alter_task_last_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="ipv6_prefix_length",
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv4_last_address",
            new_name="ipv4_previous_address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv6_last_address",
            new_name="ipv6_previous_address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv4_address",
            new_name="ipv4_last_address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv4_last_change_time",
            new_name="ipv4_last_change_time",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv6_address",
            new_name="ipv6_last_address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="ipv6_last_change_time",
            new_name="ipv6_last_change_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="ip_addresses",
        ),
        migrations.AddField(
            model_name="task",
            name="previous_ip_addresses",
            field=models.TextField(max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_ip_addresses",
            field=models.CharField(default=django.utils.timezone.now, max_length=62),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="last_update_success_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="last_update_is_success",
            new_name="last_update_success",
        ),
        migrations.AlterField(
            model_name="task",
            name="last_update_success",
            field=models.BooleanField(default=False),
        ),
    ]
