# Generated by Django 3.2.9 on 2021-12-02 04:16

import ddns_clienter_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddns_clienter_core", "0002_alter_domain_last_ip_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.TextField(verbose_name=ddns_clienter_core.models.EventLevel),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
