# Generated by Django 4.0.2 on 2022-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0004_address_allow_loopback_address_allow_private"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="provider_token",
            new_name="provider_auth",
        ),
    ]
