# Generated by Django 3.2.9 on 2021-12-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddns_clienter_core", "0004_alter_event_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="level",
            field=models.TextField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("CRITICAL", "Critical"),
                ]
            ),
        ),
    ]
