# Generated by Django 4.1.7 on 2023-02-28 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0005_rename_provider_token_task_provider_auth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="provider",
            new_name="provider_name",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="parameter",
            new_name="provider_parameter",
        ),
    ]
