# Generated by Django 4.1.7 on 2023-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0006_rename_provider_address_provider_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="enable",
            field=models.BooleanField(default=True),
        ),
    ]
