# Generated by Django 4.1.7 on 2023-02-28 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0007_task_enable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="provider",
            new_name="provider_name",
        ),
    ]
