# Generated by Django 4.1.7 on 2023-03-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddns_clienter_core", "0008_rename_provider_task_provider_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="enable",
            field=models.BooleanField(default=True),
        ),
    ]
