# Generated by Django 5.2.5 on 2025-08-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddns_clienter_core", "0009_address_enable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="host",
        ),
    ]
